name = "VoxelRayTracers"
uuid = "d9e3e1c4-15df-46c7-bfdb-139154feb7ae"
authors = ["Jan Weidner <jw3126@gmail.com>"]
version = "0.1.3"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
ArgCheck = "1, 2.0"
RecipesBase = "0.7, 0.8"
julia = "1.3"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
